[project]
name = "web-to-markdown-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crawl4ai>=0.6.3",
]

[project.scripts]
convert = "main:main"

[tool.uv]
package = true
