import soundfile as sf
import sys
from kokoro_onnx import Kokoro

# --- Configuration ---
MODEL_FILENAME = "kokoro-v1.0.onnx"
VOICES_FILENAME = "voices-v1.0.bin"
OUTPUT_FILENAME = "output_audio.wav"
TEXT_TO_SYNTHESIZE = "Hello. This audio was generated by Kokoro ONNX on an M1 Mac!"
VOICE_ID = "af_sarah" # Example voice, see https://huggingface.co/hexgrad/Kokoro-82M/blob/main/VOICES.md
# Available Voices (from VOICES.md):
# American English (lang_code='a'):
#   af_heart, af_alloy, af_aoede, af_bella, af_jessica, af_kore, af_nicole, af_nova, af_river, af_sarah, af_sky
#   am_adam, am_echo, am_eric, am_fenrir, am_liam, am_michael, am_onyx, am_puck, am_santa
# British English (lang_code='b'):
#   bf_alice, bf_emma, bf_isabella, bf_lily
#   bm_daniel, bm_fable, bm_george, bm_lewis
# Japanese (lang_code='j'):
#   jf_alpha, jf_gongitsune, jf_nezumi, jf_tebukuro
#   jm_kumo
# Mandarin Chinese (lang_code='z'):
#   zf_xiaobei, zf_xiaoni, zf_xiaoxiao, zf_xiaoyi
#   zm_yunjian, zm_yunxi, zm_yunxia, zm_yunyang
# Spanish (lang_code='e'):
#   ef_dora
#   em_alex, em_santa
# French (lang_code='f'):
#   ff_siwis
# Hindi (lang_code='h'):
#   hf_alpha, hf_beta
#   hm_omega, hm_psi
# Italian (lang_code='i'):
#   if_sara
#   im_nicola
# Brazilian Portuguese (lang_code='p'):
#   pf_dora
#   pm_alex, pm_santa
LANGUAGE_CODE = "en-us" # Example language
SPEED = 1.0

def main():
    """Loads the Kokoro ONNX model and generates audio."""

    print(f"Loading Kokoro model: {MODEL_FILENAME}")
    print(f"Loading voices: {VOICES_FILENAME}")

    try:
        # Initialize Kokoro with model and voice files
        # The kokoro-onnx package handles ONNX Runtime session creation
        # and provider selection internally. It should automatically
        # attempt to use CoreML on macOS if available.
        kokoro = Kokoro(MODEL_FILENAME, VOICES_FILENAME)
        print("Kokoro model loaded successfully.")

    except FileNotFoundError:
        print(f"Error: Model file '{MODEL_FILENAME}' or voices file '{VOICES_FILENAME}' not found.", file=sys.stderr)
        print("Please download them from https://github.com/thewh1teagle/kokoro-onnx/releases", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error initializing Kokoro: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"\nSynthesizing text: '{TEXT_TO_SYNTHESIZE}'")
    print(f"Using voice: {VOICE_ID}")
    print(f"Using language: {LANGUAGE_CODE}")
    print(f"Speed: {SPEED}")

    try:
        # Generate audio samples
        samples, sample_rate = kokoro.create(
            TEXT_TO_SYNTHESIZE,
            voice=VOICE_ID,
            speed=SPEED,
            lang=LANGUAGE_CODE
        )
        print(f"Audio generated with sample rate: {sample_rate}")

        # Save the audio to a WAV file
        sf.write(OUTPUT_FILENAME, samples, sample_rate)
        print(f"Audio saved to '{OUTPUT_FILENAME}'")

    except ValueError as e:
        print(f"Error during synthesis: {e}", file=sys.stderr)
        print("Check if the voice ID and language code are valid.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred during synthesis: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
